spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8787
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: productservice_db_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
